# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3e741196f23cc130016a7ccf4df2ff57a059b324595b917377802d226e9920f9a0c43db8ad79e1716cf2e3f94d35f195ddee0766a0aae56fa3b6eecd150107

test:
  secret_key_base: e911fb5861d315c5ffbfca90fdbe7a02a4adf1f902686c01cc0e09519373839ceb04fbb5623c7ed08d9b99dcf218ebe4081ec8bdfba9cc94c3f4446ae4facf4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
